### ISSUE TITLE
查询不到数据？

### ISSUE THREAD

**Issue by RyanYans** [Airsaid/AccountBook#10]
访问提示：查询不到数据
error code：{"code":101,"error":"Class or object doesn't exists."}？

**Comment by Airsaid** [comment]
请看下这个答案能否解决问题：

https://github.com/Airsaid/AccountBook/issues/3

**Comment by RyanYans** [comment]
[#8](https://github.com/Airsaid/AccountBook/issues/8)
同样问题，无法解决

id和key已经配置过。在云端也是有记录的 但是登录不进去
/com.github.airsaid.accountbook D/===AVOS Cloud===: LogUtil$avlog->d->33: {"code":101,"error":"Class or object doesn't exists."}
关闭应用重新打开，奇迹般的进去了 但是不能保存 收入支出的数据 toast显示查询不到数据
com.github.airsaid.accountbook D/===AVOS Cloud===: LogUtil$avlog->d->33: {"code":101,"error":"Class or object doesn't exists."}
还是显示这个错误 请大牛在readme上面做下补充吧

**Comment by Airsaid** [comment]
短信开关是否打开？

「启用通用的短信验证码服务（开放 requestSmsCode 和 verifySmsCode 接口）」

**Comment by newcaoguo** [comment]
没有解决额
