### ISSUE TITLE
无法保存账目，点击完成记账会卡死

### ISSUE THREAD

**Issue by ghost** [Airsaid/AccountBook#17]
04-26 00:47:43.588 23438-23438/com.sue.classmatealumni D/===AVOS Cloud===: LogUtil$avlog->d->33: curl -X GET -H "X-LC-Id: Ajbyt6n4VCMl9CUNtD27DCsD-gzGzoHsz" -H "X-LC-Key: YourAppKey" -G --data-urlencode 'where={"isCurrent":true,"owner":{"__type":"Pointer","className":"_User","objectId":"5ae9a6429f545400402748bc"}}' https://api.leancloud.cn/1.1/classes/AccountBook
04-26 00:47:43.589 23438-23531/com.sue.classmatealumni D/===AVOS Cloud===: LogUtil$avlog->d->33: {"results":[{"updatedAt":"2018-05-02T11:52:06.245Z","name":"\u65e5\u5e38\u5e10\u8584","objectId":"5ae9a666a22b9d004428dcd9","cover":"book_icon1","createdAt":"2018-05-02T11:52:06.242Z","isCurrent":true,"shares":[{"__type":"Pointer","className":"_User","objectId":"5ae9a6429f545400402748bc"}],"owner":{"__type":"Pointer","className":"_User","objectId":"5ae9a6429f545400402748bc"},"scene":"\u65e5\u5e38"}]}

**Comment by Airsaid** [comment]
你好，请查看：#18
