### ISSUE TITLE
能够注册，不能登陆

### ISSUE THREAD

**Issue by dongwuxin** [Airsaid/AccountBook#18]
能够注册，不能登陆

**Comment by Airsaid** [comment]
已经修复该问题，请重新拉下最新的代码并按照如下步骤操作：

1，删除 LeanCloud 后台中 AccountBook、Account 表。（如果有的话）
2，重新卸载原有应用并重新安装最新代码的应用。
3，登录成功后，在 LeanCloud 后台设置 AccountBook 表中的 bid 字段，勾选上「自增」。

**Comment by dongwuxin** [comment]
谢谢大佬
