### ISSUE TITLE
登录失败。

### ISSUE THREAD

**Issue by android-cui** [Airsaid/AccountBook#3]
返回信息：{"code":101,"error":"Class or object doesn't exists."}

**Comment by Airsaid** [comment]
您好，关于这个问题请检查 LeanCloud 的配置是否正确。

1、appkey、id 是否一致。
2，后台服务开关是否开启。（如下图）
3，应用选项中用户账号服务是否勾选。（如下图）

![qq 20170527101858](https://cloud.githubusercontent.com/assets/15967150/26517184/f947a1e0-42c5-11e7-8821-0bb5fa3f7d44.png)
![qq 20170527101842](https://cloud.githubusercontent.com/assets/15967150/26517185/000ad33a-42c6-11e7-8752-d2c8e19c464b.png)

**Comment by android-cui** [comment]
ok,可以登录了。

**Comment by newcaoguo** [comment]
我的不能啊

**Comment by SNXJ** [comment]
配置改了！我试了下也不行！
