### ISSUE TITLE
发现两个新问题

### ISSUE THREAD

**Issue by android-cui** [Airsaid/AccountBook#4]
一：无法添加今天的记事数据，提示查询不到数据。
 二：屏幕自动旋转软件秒退。  使用环境，Android 7.1.2    Nexus5X

**Comment by Airsaid** [comment]
你好，感谢反馈。关于这二个问题，我并没有复现成功。

另外如果在真机情况下，第二个问题所说的屏幕旋转问题应该是不可能出现的，因为已经在 BaseActivity 中设置屏幕方向为竖屏显示：

`setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);`
