### ISSUE TITLE
数据有误，测试不通过

### ISSUE THREAD

**Issue by baowenqing** [Airsaid/AccountBook#8]
id和key已经配置过。在云端也是有记录的 但是登录不进去 
/com.github.airsaid.accountbook D/===AVOS Cloud===: LogUtil$avlog->d->33: {"code":101,"error":"Class or object doesn't exists."}
关闭应用重新打开，奇迹般的进去了 但是不能保存 收入支出的数据 toast显示查询不到数据
com.github.airsaid.accountbook D/===AVOS Cloud===: LogUtil$avlog->d->33: {"code":101,"error":"Class or object doesn't exists."}
还是显示这个错误 请大牛在readme上面做下补充吧

**Comment by Airsaid** [comment]
您好，请参照下这个 Issues 进行配置：[https://github.com/Airsaid/AccountBook/issues/3](https://github.com/Airsaid/AccountBook/issues/3)，看看配置后问题是否能够解决。

**Comment by Airsaid** [comment]
已在 Readme 上面做了相应补充。如果还有问题，您可以再次开启这个 issue。
