### ISSUE TITLE
红米Note1S 安装后闪退

### ISSUE THREAD

**Issue by yjandroid** [Airsaid/AccountBook#9]
红米Note1S 
运行安装后，引导页到注册页时闪退，无任何提示。AndroidStudio上也没有错误Log。
手机系统为安卓4.4.4

**Comment by Airsaid** [comment]
style 的原因导致，没有对 5.0 下进行兼容。其实兼容很简单，我只是懒而已...  如果需要的话我可以抽空兼容一下。
